CUDA_VISIBLE_DEVICES=0 python train_clm.py \
    --model_name_or_path /home/wenyanghui/plms/baichuan2-7B-chat \
    --task mathqa \
    --do_train \
    --do_eval \
    --label_names labels \
    --load_in_8bit \
    --block_size 512 \
    --per_device_train_batch_size 1 \
    --num_train_epochs 20 \
    --learning_rate 8e-5 \
    --save_total_limit 3 \
    --load_best_model_at_end True \
    --save_strategy epoch \
    --evaluation_strategy epoch \
    --auto_find_batch_size \
    --output_dir . \
    --bf16 \
    --use_lora